name: vaultnote
description: Offline secure vault for passwords and notes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0 #^9.2.2
  local_auth: ^2.3.0
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  path_provider: ^2.1.4
  crypto: ^3.0.5
  share_plus: ^10.0.0
  flutter_windowmanager: ^0.2.0
  file_picker: ^8.1.2
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true